"""empty message

Revision ID: 62df0554709a
Revises: 
Create Date: 2023-10-16 09:40:43.339356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62df0554709a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.Column('selectedDate', sa.String(length=255), nullable=False),
    sa.Column('selectedTime', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('answers', sa.String(length=5000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intakeform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('answers', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('valid_id', sa.String(length=100), nullable=False),
    sa.Column('pay_stub', sa.String(length=255), nullable=False),
    sa.Column('school_registration', sa.String(length=255), nullable=False),
    sa.Column('bank_statement', sa.String(length=255), nullable=False),
    sa.Column('credit_report', sa.String(length=255), nullable=False),
    sa.Column('reccomendation_letter', sa.String(length=255), nullable=False),
    sa.Column('employer_letter', sa.String(length=255), nullable=False),
    sa.Column('subsidy_letter', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload')
    op.drop_table('intakeform')
    op.drop_table('buyform')
    op.drop_table('appointment')
    # ### end Alembic commands ###
