"""empty message

Revision ID: edef8b5a4cec
Revises: 62df0554709a
Create Date: 2023-10-16 10:06:31.521763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edef8b5a4cec'
down_revision = '62df0554709a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('files', sa.String(length=100), nullable=False))
        batch_op.drop_column('valid_id')
        batch_op.drop_column('credit_report')
        batch_op.drop_column('school_registration')
        batch_op.drop_column('employer_letter')
        batch_op.drop_column('bank_statement')
        batch_op.drop_column('reccomendation_letter')
        batch_op.drop_column('pay_stub')
        batch_op.drop_column('subsidy_letter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subsidy_letter', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('pay_stub', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('reccomendation_letter', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('bank_statement', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('employer_letter', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('school_registration', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('credit_report', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('valid_id', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('files')

    # ### end Alembic commands ###
